title:    "Jesus Molina"
author:   Jesus Molina
email:    contact@jesusmolina.com
lsi:      false
highlighter: pygments
auto: true
server: true
port: 4000
baseurl:    /
url: http://www.jesusmolina.com
markdown: Kramdown 
url_root: http://www.jesumolina.com
